
[7m[1m[34m DEV [39m[22m[27m [34mv2.1.3[39m [90mC:/Users/Inna/Desktop/storinky-server[39m

[90mstdout[2m | tests/app.test.ts[22m[39m
Connected to MongoDB
Server running on port 8080
Swagger docs: http://localhost:8080/api-docs

::ffff:127.0.0.1 - GET / HTTP/1.1 200 39 - 1.383 ms
 [32m‚úì[39m tests/app.test.ts [2m ([22m[2m1 test[22m[2m)[22m[90m 16[2mms[22m[39m
[90mstdout[2m | tests/book/book.test.ts[22m[39m
Connected to MongoDB
Server running on port 8080
Swagger docs: http://localhost:8080/api-docs

::ffff:127.0.0.1 - GET /api/book/64f1a89c6c6b1e5d59c1a79e HTTP/1.1 200 149 - 2.210 ms
[90mstdout[2m | tests/book/book.test.ts[2m > [22m[2mBooks API with mock[2m > [22m[2mshould return 200 and the book for a valid existing ID[22m[39m
Validating ID: 64f1a89c6c6b1e5d59c1a79e

::ffff:127.0.0.1 - GET /api/book/incorrect-id HTTP/1.1 400 26 - 1.012 ms
[90mstdout[2m | tests/book/book.test.ts[2m > [22m[2mBooks API with mock[2m > [22m[2mshould return 400 if ID format is invalid[22m[39m
Validating ID: incorrect-id

[90mstdout[2m | tests/book/book.test.ts[2m > [22m[2mBooks API with mock[2m > [22m[2mshould return 404 if book is not found[22m[39m
Validating ID: 64f1a89c6c6b1e5d59c1a79e

::ffff:127.0.0.1 - GET /api/book/64f1a89c6c6b1e5d59c1a79e HTTP/1.1 404 23 - 67.428 ms
::ffff:127.0.0.1 - GET /api/book HTTP/1.1 200 267 - 0.270 ms
::ffff:127.0.0.1 - GET /api/book/pages?page=1&limit=1 HTTP/1.1 200 146 - 0.343 ms
::ffff:127.0.0.1 - GET /api/book/search?search=Search HTTP/1.1 200 137 - 0.305 ms
::ffff:127.0.0.1 - GET /api/book/search HTTP/1.1 400 58 - 0.151 ms
::ffff:127.0.0.1 - GET /api/book/search?search=Nonexistent HTTP/1.1 404 29 - 0.195 ms
::ffff:127.0.0.1 - PUT /api/book/64f1a89c6c6b1e5d59c1a79e HTTP/1.1 400 31 - 0.425 ms
[90mstdout[2m | tests/book/book.test.ts[2m > [22m[2mBooks API with mock[2m > [22m[2mshould return 200 and update the book[22m[39m
Response: { message: [32m'Token is required'[39m }

::ffff:127.0.0.1 - PUT /api/book/64f1a89c6c6b1e5d59c1a79e HTTP/1.1 400 31 - 0.342 ms
[90mstdout[2m | tests/book/book.test.ts[2m > [22m[2mBooks API with mock[2m > [22m[2mshould return 422 if required fields are missing[22m[39m
Validation Error Response: { message: [32m'Token is required'[39m }

::ffff:127.0.0.1 - PUT /api/book/64f1a89c6c6b1e5d59c1a79e HTTP/1.1 400 31 - 1.973 ms
[90mstdout[2m | tests/book/book.test.ts[2m > [22m[2mBooks API with mock[2m > [22m[2mshould return 404 if book is not found[22m[39m
404 Error Response: { message: [32m'Token is required'[39m }

 [31m‚ùØ[39m tests/book/book.test.ts [2m ([22m[2m11 tests[22m [2m|[22m [31m3 failed[39m[2m)[22m[90m 139[2mms[22m[39m
[31m   [31m√ó[31m Books API with mock[2m > [22mshould return 200 and update the book[39m
[31m     ‚Üí expected 400 to be 200 // Object.is equality[39m
[31m   [31m√ó[31m Books API with mock[2m > [22mshould return 422 if required fields are missing[39m
[31m     ‚Üí expected 400 to be 422 // Object.is equality[39m
[31m   [31m√ó[31m Books API with mock[2m > [22mshould return 404 if book is not found[39m
[31m     ‚Üí expected 400 to be 404 // Object.is equality[39m
[90mstdout[2m | tests/email/email.test.ts[22m[39m
Connected to MongoDB
Server running on port 8080
Swagger docs: http://localhost:8080/api-docs

[90mstdout[2m | tests/auth/auth.test.ts[22m[39m
Connected to MongoDB

::ffff:127.0.0.1 - POST /api/email/email-address HTTP/1.1 400 39 - 1.491 ms
::ffff:127.0.0.1 - POST /api/email/email-address HTTP/1.1 400 39 - 0.360 ms
::ffff:127.0.0.1 - POST /api/email/email-address HTTP/1.1 400 35 - 0.313 ms
::ffff:127.0.0.1 - POST /api/email/email-address HTTP/1.1 409 42 - 66.900 ms
::ffff:127.0.0.1 - POST /api/email/email-address HTTP/1.1 201 36 - 81.564 ms
::ffff:127.0.0.1 - POST /api/email/email-address HTTP/1.1 500 35 - 0.367 ms
::ffff:127.0.0.1 - POST /api/auth/register HTTP/1.1 201 175 - 240.575 ms
::ffff:127.0.0.1 - POST /api/auth/register HTTP/1.1 409 33 - 48.720 ms
::ffff:127.0.0.1 - POST /api/auth/register HTTP/1.1 422 56 - 1.316 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mregister[2m > [22m[2mshould return 422 if username is not provided[22m[39m
Validation Error: "username" is required

::ffff:127.0.0.1 - POST /api/auth/register HTTP/1.1 422 71 - 0.596 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mregister[2m > [22m[2mshould return 422 if username is empty[22m[39m
Validation Error: "username" is not allowed to be empty

::ffff:127.0.0.1 - POST /api/auth/register HTTP/1.1 422 68 - 0.491 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mregister[2m > [22m[2mshould return 422 if email is empty[22m[39m
Validation Error: "email" is not allowed to be empty

::ffff:127.0.0.1 - POST /api/auth/register HTTP/1.1 422 201 - 0.515 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mregister[2m > [22m[2mshould return 422 if email is not valid[22m[39m
Validation Error: "email" with value "invalid@email" fails to match the required pattern: /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i

::ffff:127.0.0.1 - POST /api/auth/register HTTP/1.1 422 164 - 0.410 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mregister[2m > [22m[2mshould return 422 if password is not strong enough[22m[39m
Validation Error: "password" with value "password" fails to match the required pattern: /^((?=\S*?[A-Z])(?=\S*?[a-z])(?=\S*?[0-9]).{8,20})\S$/

::ffff:127.0.0.1 - POST /api/auth/register HTTP/1.1 500 28 - 0.634 ms
::ffff:127.0.0.1 - POST /api/auth/login HTTP/1.1 200 168 - 107.264 ms
::ffff:127.0.0.1 - POST /api/auth/login HTTP/1.1 422 53 - 0.531 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mlogin[2m > [22m[2mshould return 400 if email is not provided[22m[39m
Validation Error: "email" is required

::ffff:127.0.0.1 - POST /api/auth/login HTTP/1.1 422 56 - 0.426 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mlogin[2m > [22m[2mshould return 400 if password is not provided[22m[39m
Validation Error: "password" is required

::ffff:127.0.0.1 - POST /api/auth/login HTTP/1.1 401 39 - 47.440 ms
::ffff:127.0.0.1 - POST /api/auth/login HTTP/1.1 500 28 - 0.504 ms
::ffff:127.0.0.1 - GET /api/auth/refresh HTTP/1.1 200 116 - 55.868 ms
::ffff:127.0.0.1 - GET /api/auth/refresh HTTP/1.1 400 31 - 0.296 ms
::ffff:127.0.0.1 - GET /api/auth/refresh HTTP/1.1 401 32 - 0.239 ms
::ffff:127.0.0.1 - GET /api/auth/refresh HTTP/1.1 500 28 - 0.822 ms
::ffff:127.0.0.1 - GET /api/auth/logout HTTP/1.1 200 31 - 49.649 ms
::ffff:127.0.0.1 - GET /api/auth/logout HTTP/1.1 400 31 - 0.352 ms
::ffff:127.0.0.1 - GET /api/auth/logout HTTP/1.1 401 32 - 0.227 ms
::ffff:127.0.0.1 - GET /api/auth/logout HTTP/1.1 500 28 - 0.954 ms
::ffff:127.0.0.1 - PATCH /api/auth/reset-password/invalid-token HTTP/1.1 422 56 - 0.641 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mresetPassword[2m > [22m[2mshould return 422 if password is not provided[22m[39m
Validation Error: "password" is required

::ffff:127.0.0.1 - PATCH /api/auth/reset-password/invalid-token HTTP/1.1 422 63 - 0.462 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mresetPassword[2m > [22m[2mshould return 422 if confirmPassword is not provided[22m[39m
Validation Error: "confirmPassword" is required

::ffff:127.0.0.1 - PATCH /api/auth/reset-password/invalid-token HTTP/1.1 400 47 - 49.870 ms
 [32m‚úì[39m tests/auth/auth.test.ts [2m ([22m[2m24 tests[22m[2m)[22m[33m 868[2mms[22m[39m
::ffff:127.0.0.1 - POST /api/email/forget-password HTTP/1.1 500 48 - 2230.106 ms
::ffff:127.0.0.1 - POST /api/email/forget-password HTTP/1.1 422 53 - 1.077 ms
[90mstdout[2m | tests/email/email.test.ts[2m > [22m[2mEmailController[2m > [22m[2mforgotPassword[2m > [22m[2mshould return 422 if email is not provided[22m[39m
Validation Error: "email" is required

::ffff:127.0.0.1 - POST /api/email/forget-password HTTP/1.1 422 68 - 0.509 ms
[90mstdout[2m | tests/email/email.test.ts[2m > [22m[2mEmailController[2m > [22m[2mforgotPassword[2m > [22m[2mshould return 422 if email is empty[22m[39m
Validation Error: "email" is not allowed to be empty

::ffff:127.0.0.1 - POST /api/email/forget-password HTTP/1.1 422 201 - 0.477 ms
[90mstdout[2m | tests/email/email.test.ts[2m > [22m[2mEmailController[2m > [22m[2mforgotPassword[2m > [22m[2mshould return 422 for invalid email format[22m[39m
Validation Error: "email" with value "invalid@email" fails to match the required pattern: /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i

::ffff:127.0.0.1 - POST /api/email/forget-password HTTP/1.1 404 63 - 50.464 ms
 [31m‚ùØ[39m tests/email/email.test.ts [2m ([22m[2m11 tests[22m [2m|[22m [31m1 failed[39m[2m)[22m[33m 2661[2mms[22m[39m
[31m   [31m√ó[31m EmailController[2m > [22mforgotPassword[2m > [22mshould return 200 if email is sent successfully[39m
[31m     ‚Üí expected 500 to be 200 // Object.is equality[39m

[31m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[1m[7m Failed Tests 4 [27m[22m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[39m

[31m[1m[7m FAIL [27m[22m[39m tests/book/book.test.ts[2m > [22mBooks API with mock[2m > [22mshould return 200 and update the book
[31m[1mAssertionError[22m: expected 400 to be 200 // Object.is equality[39m

[32m- Expected[39m
[31m+ Received[39m

[32m- 200[39m
[31m+ 400[39m

[36m [2m‚ùØ[22m tests/book/book.test.ts:[2m153:24[22m[39m
    [90m151| [39m
    [90m152| [39m    console[33m.[39m[34mlog[39m([32m"Response:"[39m[33m,[39m res[33m.[39mbody)[33m;[39m
    [90m153| [39m    [34mexpect[39m(res[33m.[39mstatus)[33m.[39m[34mtoBe[39m([34m200[39m)[33m;[39m
    [90m   | [39m                       [31m^[39m
    [90m154| [39m    [34mexpect[39m(res[33m.[39mbody[33m.[39mtitle[[34m0[39m][33m.[39men)[33m.[39m[34mtoBe[39m([32m"Updated Title"[39m)[33m;[39m
    [90m155| [39m    [34mexpect[39m(res[33m.[39mbody[33m.[39mauthor[[34m0[39m])[33m.[39m[34mtoBe[39m([32m"Updated Author"[39m)[33m;[39m

[31m[2m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[1/4]‚éØ[22m[39m

[31m[1m[7m FAIL [27m[22m[39m tests/book/book.test.ts[2m > [22mBooks API with mock[2m > [22mshould return 422 if required fields are missing
[31m[1mAssertionError[22m: expected 400 to be 422 // Object.is equality[39m

[32m- Expected[39m
[31m+ Received[39m

[32m- 422[39m
[31m+ 400[39m

[36m [2m‚ùØ[22m tests/book/book.test.ts:[2m163:24[22m[39m
    [90m161| [39m
    [90m162| [39m    console[33m.[39m[34mlog[39m([32m"Validation Error Response:"[39m[33m,[39m res[33m.[39mbody)[33m;[39m
    [90m163| [39m    [34mexpect[39m(res[33m.[39mstatus)[33m.[39m[34mtoBe[39m([34m422[39m)[33m;[39m
    [90m   | [39m                       [31m^[39m
    [90m164| [39m    [34mexpect[39m(res[33m.[39mbody[33m.[39mmessage)[33m.[39m[34mtoContain[39m([32m"Validation error"[39m)[33m;[39m
    [90m165| [39m  })[33m;[39m

[31m[2m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[2/4]‚éØ[22m[39m

[31m[1m[7m FAIL [27m[22m[39m tests/book/book.test.ts[2m > [22mBooks API with mock[2m > [22mshould return 404 if book is not found
[31m[1mAssertionError[22m: expected 400 to be 404 // Object.is equality[39m

[32m- Expected[39m
[31m+ Received[39m

[32m- 404[39m
[31m+ 400[39m

[36m [2m‚ùØ[22m tests/book/book.test.ts:[2m182:24[22m[39m
    [90m180| [39m
    [90m181| [39m    console[33m.[39m[34mlog[39m([32m"404 Error Response:"[39m[33m,[39m res[33m.[39mbody)[33m;[39m
    [90m182| [39m    [34mexpect[39m(res[33m.[39mstatus)[33m.[39m[34mtoBe[39m([34m404[39m)[33m;[39m
    [90m   | [39m                       [31m^[39m
    [90m183| [39m    [34mexpect[39m(res[33m.[39mbody[33m.[39mmessage)[33m.[39m[34mtoBe[39m([32m"Not found"[39m)[33m;[39m
    [90m184| [39m  })[33m;[39m

[31m[2m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[3/4]‚éØ[22m[39m

[31m[1m[7m FAIL [27m[22m[39m tests/email/email.test.ts[2m > [22mEmailController[2m > [22mforgotPassword[2m > [22mshould return 200 if email is sent successfully
[31m[1mAssertionError[22m: expected 500 to be 200 // Object.is equality[39m

[32m- Expected[39m
[31m+ Received[39m

[32m- 200[39m
[31m+ 500[39m

[36m [2m‚ùØ[22m tests/email/email.test.ts:[2m101:31[22m[39m
    [90m 99| [39m        [33m.[39m[34msend[39m({ email[33m:[39m validEmail })[33m;[39m
    [90m100| [39m
    [90m101| [39m      [34mexpect[39m(response[33m.[39mstatus)[33m.[39m[34mtoBe[39m([34m200[39m)[33m;[39m
    [90m   | [39m                              [31m^[39m
    [90m102| [39m      [34mexpect[39m(response[33m.[39mbody[33m.[39mmessage)[33m.[39m[34mtoBe[39m(
    [90m103| [39m        [32m"Email for reset password sent successfully"[39m[33m,[39m

[31m[2m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[4/4]‚éØ[22m[39m

[31m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[1m[7m Unhandled Errors [27m[22m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[39m
[31m[1m
Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.[22m[39m

[31m‚éØ‚éØ‚éØ‚éØ‚éØ[1m[7m Uncaught Exception [27m[22m‚éØ‚éØ‚éØ‚éØ‚éØ[39m
[31m[1mError[22m: listen EADDRINUSE: address already in use :::8080[39m
[90m [2m‚ùØ[22m Server.setupListenHandle [as _listen2] node:net:[2m1898:16[22m[39m
[90m [2m‚ùØ[22m listenInCluster node:net:[2m1946:12[22m[39m
[90m [2m‚ùØ[22m Server.listen node:net:[2m2044:7[22m[39m
[90m [2m‚ùØ[22m Function.listen node_modules/express/lib/application.js:[2m635:24[22m[39m
[36m [2m‚ùØ[22m src/app.ts:[2m94:20[22m[39m
    [90m 92| [39m  })[33m;[39m
    [90m 93| [39m
    [90m 94| [39m[35mconst[39m server [33m=[39m app[33m.[39m[34mlisten[39m([33mPORT[39m[33m,[39m () [33m=>[39m {
    [90m   | [39m                   [31m^[39m
    [90m 95| [39m  console[33m.[39m[34mlog[39m([32m`Server running on port [39m[36m${[39m[33mPORT[39m[36m}[39m[32m`[39m)[33m;[39m
    [90m 96| [39m  console[33m.[39m[34mlog[39m([32m`Swagger docs: http://localhost:[39m[36m${[39m[33mPORT[39m[36m}[39m[32m/api-docs`[39m)[33m;[39m
[90m [2m‚ùØ[22m processTicksAndRejections node:internal/process/task_queues:[2m95:5[22m[39m
[90m [2m‚ùØ[22m VitestExecutor.runModule node_modules/vite-node/dist/client.mjs:[2m399:5[22m[39m
[90m [2m‚ùØ[22m VitestExecutor.directRequest node_modules/vite-node/dist/client.mjs:[2m381:5[22m[39m
[90m [2m‚ùØ[22m VitestExecutor.cachedRequest node_modules/vite-node/dist/client.mjs:[2m206:14[22m[39m
[90m [2m‚ùØ[22m VitestExecutor.dependencyRequest node_modules/vite-node/dist/client.mjs:[2m259:12[22m[39m

[31m[2m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[22m[39m
[31m[1mSerialized Error:[22m[39m [90m{ code: 'EADDRINUSE', errno: -4091, syscall: 'listen', address: '::', port: 8080 }[39m
[31mThis error originated in "[1mtests/auth/auth.test.ts[22m" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.[39m
[31mThe latest test that might've caused the error is "[1mtests/auth/auth.test.ts[22m". It might mean one of the following:
- The error was thrown, while Vitest was running this test.
- If the error occurred after the test had been completed, this was the last documented test before it was thrown.[39m
[31m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[39m

[2m Test Files [22m [1m[31m2 failed[39m[22m[2m | [22m[1m[32m2 passed[39m[22m[90m (4)[39m
[2m      Tests [22m [1m[31m4 failed[39m[22m[2m | [22m[1m[32m43 passed[39m[22m[90m (47)[39m
[2m     Errors [22m [1m[31m1 error[39m[22m
[2m   Start at [22m 20:22:29
[2m   Duration [22m 6.94s[2m (transform 300ms, setup 0ms, collect 11.81s, tests 3.68s, environment 1ms, prepare 387ms)[22m


[1m[7m[31m FAIL [39m[27m[22m[31m Tests failed. Watching for file changes...[39m
       [2mpress [22m[1mh[22m[2m to show help[22m[2m, [22m[2mpress [22m[1mq[22m[2m to quit[22m
c[3J
[7m[1m[34m RERUN [39m[22m[27m[2m rerun all tests[22m

[90mstdout[2m | tests/email/email.test.ts[22m[39m
Connected to MongoDB
Server running on port 8080
Swagger docs: http://localhost:8080/api-docs

[90mstdout[2m | tests/auth/auth.test.ts[22m[39m
Connected to MongoDB

[90mstdout[2m | tests/book/book.test.ts[22m[39m
Connected to MongoDB

[90mstdout[2m | tests/app.test.ts[22m[39m
Connected to MongoDB

::ffff:127.0.0.1 - GET / HTTP/1.1 200 39 - 1.441 ms
::ffff:127.0.0.1 - GET /api/book/64f1a89c6c6b1e5d59c1a79e HTTP/1.1 200 149 - 2.239 ms
[90mstdout[2m | tests/book/book.test.ts[2m > [22m[2mBooks API with mock[2m > [22m[2mshould return 200 and the book for a valid existing ID[22m[39m
Validating ID: 64f1a89c6c6b1e5d59c1a79e

 [32m‚úì[39m tests/app.test.ts [2m ([22m[2m1 test[22m[2m)[22m[90m 17[2mms[22m[39m
::ffff:127.0.0.1 - GET /api/book/incorrect-id HTTP/1.1 400 26 - 0.910 ms
[90mstdout[2m | tests/book/book.test.ts[2m > [22m[2mBooks API with mock[2m > [22m[2mshould return 400 if ID format is invalid[22m[39m
Validating ID: incorrect-id

[90mstdout[2m | tests/book/book.test.ts[2m > [22m[2mBooks API with mock[2m > [22m[2mshould return 404 if book is not found[22m[39m
Validating ID: 64f1a89c6c6b1e5d59c1a79e

::ffff:127.0.0.1 - GET /api/book/64f1a89c6c6b1e5d59c1a79e HTTP/1.1 404 23 - 84.781 ms
::ffff:127.0.0.1 - GET /api/book HTTP/1.1 200 267 - 0.960 ms
::ffff:127.0.0.1 - GET /api/book/pages?page=1&limit=1 HTTP/1.1 200 146 - 1.150 ms
::ffff:127.0.0.1 - GET /api/book/search?search=Search HTTP/1.1 200 137 - 0.426 ms
::ffff:127.0.0.1 - GET /api/book/search HTTP/1.1 400 58 - 0.209 ms
::ffff:127.0.0.1 - GET /api/book/search?search=Nonexistent HTTP/1.1 404 29 - 0.307 ms
::ffff:127.0.0.1 - PUT /api/book/64f1a89c6c6b1e5d59c1a79e HTTP/1.1 400 31 - 1.030 ms
::ffff:127.0.0.1 - POST /api/email/email-address HTTP/1.1 400 39 - 2.887 ms
[90mstdout[2m | tests/book/book.test.ts[2m > [22m[2mBooks API with mock[2m > [22m[2mshould return 200 and update the book[22m[39m
Response: { message: [32m'Token is required'[39m }

::ffff:127.0.0.1 - PUT /api/book/64f1a89c6c6b1e5d59c1a79e HTTP/1.1 400 31 - 0.749 ms
[90mstdout[2m | tests/book/book.test.ts[2m > [22m[2mBooks API with mock[2m > [22m[2mshould return 422 if required fields are missing[22m[39m
Validation Error Response: { message: [32m'Token is required'[39m }

::ffff:127.0.0.1 - POST /api/email/email-address HTTP/1.1 400 39 - 0.702 ms
::ffff:127.0.0.1 - PUT /api/book/64f1a89c6c6b1e5d59c1a79e HTTP/1.1 400 31 - 0.394 ms
[90mstdout[2m | tests/book/book.test.ts[2m > [22m[2mBooks API with mock[2m > [22m[2mshould return 404 if book is not found[22m[39m
404 Error Response: { message: [32m'Token is required'[39m }

 [31m‚ùØ[39m tests/book/book.test.ts [2m ([22m[2m11 tests[22m [2m|[22m [31m3 failed[39m[2m)[22m[90m 269[2mms[22m[39m
[31m   [31m√ó[31m Books API with mock[2m > [22mshould return 200 and update the book[39m
[31m     ‚Üí expected 400 to be 200 // Object.is equality[39m
[31m   [31m√ó[31m Books API with mock[2m > [22mshould return 422 if required fields are missing[39m
[31m     ‚Üí expected 400 to be 422 // Object.is equality[39m
::ffff:127.0.0.1 - POST /api/email/email-address HTTP/1.1 400 35 - 0.391 ms
[31m   [31m√ó[31m Books API with mock[2m > [22mshould return 404 if book is not found[39m
[31m     ‚Üí expected 400 to be 404 // Object.is equality[39m
::ffff:127.0.0.1 - POST /api/email/email-address HTTP/1.1 409 42 - 43.991 ms
::ffff:127.0.0.1 - POST /api/email/email-address HTTP/1.1 201 36 - 80.690 ms
::ffff:127.0.0.1 - POST /api/email/email-address HTTP/1.1 500 35 - 0.437 ms
::ffff:127.0.0.1 - POST /api/auth/register HTTP/1.1 201 175 - 204.671 ms
::ffff:127.0.0.1 - POST /api/auth/register HTTP/1.1 409 33 - 51.510 ms
::ffff:127.0.0.1 - POST /api/auth/register HTTP/1.1 422 56 - 1.208 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mregister[2m > [22m[2mshould return 422 if username is not provided[22m[39m
Validation Error: "username" is required

::ffff:127.0.0.1 - POST /api/auth/register HTTP/1.1 422 71 - 0.408 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mregister[2m > [22m[2mshould return 422 if username is empty[22m[39m
Validation Error: "username" is not allowed to be empty

::ffff:127.0.0.1 - POST /api/auth/register HTTP/1.1 422 68 - 0.350 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mregister[2m > [22m[2mshould return 422 if email is empty[22m[39m
Validation Error: "email" is not allowed to be empty

::ffff:127.0.0.1 - POST /api/auth/register HTTP/1.1 422 201 - 0.399 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mregister[2m > [22m[2mshould return 422 if email is not valid[22m[39m
Validation Error: "email" with value "invalid@email" fails to match the required pattern: /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i

::ffff:127.0.0.1 - POST /api/auth/register HTTP/1.1 422 164 - 0.350 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mregister[2m > [22m[2mshould return 422 if password is not strong enough[22m[39m
Validation Error: "password" with value "password" fails to match the required pattern: /^((?=\S*?[A-Z])(?=\S*?[a-z])(?=\S*?[0-9]).{8,20})\S$/

::ffff:127.0.0.1 - POST /api/auth/register HTTP/1.1 500 28 - 0.615 ms
::ffff:127.0.0.1 - POST /api/auth/login HTTP/1.1 200 168 - 131.189 ms
::ffff:127.0.0.1 - POST /api/auth/login HTTP/1.1 422 53 - 0.608 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mlogin[2m > [22m[2mshould return 400 if email is not provided[22m[39m
Validation Error: "email" is required

::ffff:127.0.0.1 - POST /api/auth/login HTTP/1.1 422 56 - 0.720 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mlogin[2m > [22m[2mshould return 400 if password is not provided[22m[39m
Validation Error: "password" is required

::ffff:127.0.0.1 - POST /api/auth/login HTTP/1.1 401 39 - 46.517 ms
::ffff:127.0.0.1 - POST /api/auth/login HTTP/1.1 500 28 - 0.378 ms
::ffff:127.0.0.1 - GET /api/auth/refresh HTTP/1.1 200 116 - 50.347 ms
::ffff:127.0.0.1 - GET /api/auth/refresh HTTP/1.1 400 31 - 0.218 ms
::ffff:127.0.0.1 - GET /api/auth/refresh HTTP/1.1 401 32 - 0.249 ms
::ffff:127.0.0.1 - GET /api/auth/refresh HTTP/1.1 500 28 - 0.863 ms
::ffff:127.0.0.1 - GET /api/auth/logout HTTP/1.1 200 31 - 48.430 ms
::ffff:127.0.0.1 - GET /api/auth/logout HTTP/1.1 400 31 - 0.207 ms
::ffff:127.0.0.1 - GET /api/auth/logout HTTP/1.1 401 32 - 0.223 ms
::ffff:127.0.0.1 - GET /api/auth/logout HTTP/1.1 500 28 - 0.964 ms
::ffff:127.0.0.1 - PATCH /api/auth/reset-password/invalid-token HTTP/1.1 422 56 - 0.671 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mresetPassword[2m > [22m[2mshould return 422 if password is not provided[22m[39m
Validation Error: "password" is required

::ffff:127.0.0.1 - PATCH /api/auth/reset-password/invalid-token HTTP/1.1 422 63 - 0.493 ms
[90mstdout[2m | tests/auth/auth.test.ts[2m > [22m[2mAuthController[2m > [22m[2mresetPassword[2m > [22m[2mshould return 422 if confirmPassword is not provided[22m[39m
Validation Error: "confirmPassword" is required

::ffff:127.0.0.1 - PATCH /api/auth/reset-password/invalid-token HTTP/1.1 400 47 - 48.776 ms
 [32m‚úì[39m tests/auth/auth.test.ts [2m ([22m[2m24 tests[22m[2m)[22m[33m 950[2mms[22m[39m
::ffff:127.0.0.1 - POST /api/email/forget-password HTTP/1.1 500 48 - 2234.119 ms
::ffff:127.0.0.1 - POST /api/email/forget-password HTTP/1.1 422 53 - 1.060 ms
[90mstdout[2m | tests/email/email.test.ts[2m > [22m[2mEmailController[2m > [22m[2mforgotPassword[2m > [22m[2mshould return 422 if email is not provided[22m[39m
Validation Error: "email" is required

::ffff:127.0.0.1 - POST /api/email/forget-password HTTP/1.1 422 68 - 0.534 ms
[90mstdout[2m | tests/email/email.test.ts[2m > [22m[2mEmailController[2m > [22m[2mforgotPassword[2m > [22m[2mshould return 422 if email is empty[22m[39m
Validation Error: "email" is not allowed to be empty

::ffff:127.0.0.1 - POST /api/email/forget-password HTTP/1.1 422 201 - 0.490 ms
[90mstdout[2m | tests/email/email.test.ts[2m > [22m[2mEmailController[2m > [22m[2mforgotPassword[2m > [22m[2mshould return 422 for invalid email format[22m[39m
Validation Error: "email" with value "invalid@email" fails to match the required pattern: /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i

::ffff:127.0.0.1 - POST /api/email/forget-password HTTP/1.1 404 63 - 40.584 ms
 [31m‚ùØ[39m tests/email/email.test.ts [2m ([22m[2m11 tests[22m [2m|[22m [31m1 failed[39m[2m)[22m[33m 2847[2mms[22m[39m
[31m   [31m√ó[31m EmailController[2m > [22mforgotPassword[2m > [22mshould return 200 if email is sent successfully[39m
[31m     ‚Üí expected 500 to be 200 // Object.is equality[39m

[31m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[1m[7m Failed Tests 4 [27m[22m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[39m

[31m[1m[7m FAIL [27m[22m[39m tests/book/book.test.ts[2m > [22mBooks API with mock[2m > [22mshould return 200 and update the book
[31m[1mAssertionError[22m: expected 400 to be 200 // Object.is equality[39m

[32m- Expected[39m
[31m+ Received[39m

[32m- 200[39m
[31m+ 400[39m

[36m [2m‚ùØ[22m tests/book/book.test.ts:[2m153:24[22m[39m
    [90m151| [39m
    [90m152| [39m    console[33m.[39m[34mlog[39m([32m"Response:"[39m[33m,[39m res[33m.[39mbody)[33m;[39m
    [90m153| [39m    [34mexpect[39m(res[33m.[39mstatus)[33m.[39m[34mtoBe[39m([34m200[39m)[33m;[39m
    [90m   | [39m                       [31m^[39m
    [90m154| [39m    [34mexpect[39m(res[33m.[39mbody[33m.[39mtitle[[34m0[39m][33m.[39men)[33m.[39m[34mtoBe[39m([32m"Updated Title"[39m)[33m;[39m
    [90m155| [39m    [34mexpect[39m(res[33m.[39mbody[33m.[39mauthor[[34m0[39m])[33m.[39m[34mtoBe[39m([32m"Updated Author"[39m)[33m;[39m

[31m[2m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[1/4]‚éØ[22m[39m

[31m[1m[7m FAIL [27m[22m[39m tests/book/book.test.ts[2m > [22mBooks API with mock[2m > [22mshould return 422 if required fields are missing
[31m[1mAssertionError[22m: expected 400 to be 422 // Object.is equality[39m

[32m- Expected[39m
[31m+ Received[39m

[32m- 422[39m
[31m+ 400[39m

[36m [2m‚ùØ[22m tests/book/book.test.ts:[2m163:24[22m[39m
    [90m161| [39m
    [90m162| [39m    console[33m.[39m[34mlog[39m([32m"Validation Error Response:"[39m[33m,[39m res[33m.[39mbody)[33m;[39m
    [90m163| [39m    [34mexpect[39m(res[33m.[39mstatus)[33m.[39m[34mtoBe[39m([34m422[39m)[33m;[39m
    [90m   | [39m                       [31m^[39m
    [90m164| [39m    [34mexpect[39m(res[33m.[39mbody[33m.[39mmessage)[33m.[39m[34mtoContain[39m([32m"Validation error"[39m)[33m;[39m
    [90m165| [39m  })[33m;[39m

[31m[2m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[2/4]‚éØ[22m[39m

[31m[1m[7m FAIL [27m[22m[39m tests/book/book.test.ts[2m > [22mBooks API with mock[2m > [22mshould return 404 if book is not found
[31m[1mAssertionError[22m: expected 400 to be 404 // Object.is equality[39m

[32m- Expected[39m
[31m+ Received[39m

[32m- 404[39m
[31m+ 400[39m

[36m [2m‚ùØ[22m tests/book/book.test.ts:[2m182:24[22m[39m
    [90m180| [39m
    [90m181| [39m    console[33m.[39m[34mlog[39m([32m"404 Error Response:"[39m[33m,[39m res[33m.[39mbody)[33m;[39m
    [90m182| [39m    [34mexpect[39m(res[33m.[39mstatus)[33m.[39m[34mtoBe[39m([34m404[39m)[33m;[39m
    [90m   | [39m                       [31m^[39m
    [90m183| [39m    [34mexpect[39m(res[33m.[39mbody[33m.[39mmessage)[33m.[39m[34mtoBe[39m([32m"Not found"[39m)[33m;[39m
    [90m184| [39m  })[33m;[39m

[31m[2m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[3/4]‚éØ[22m[39m

[31m[1m[7m FAIL [27m[22m[39m tests/email/email.test.ts[2m > [22mEmailController[2m > [22mforgotPassword[2m > [22mshould return 200 if email is sent successfully
[31m[1mAssertionError[22m: expected 500 to be 200 // Object.is equality[39m

[32m- Expected[39m
[31m+ Received[39m

[32m- 200[39m
[31m+ 500[39m

[36m [2m‚ùØ[22m tests/email/email.test.ts:[2m101:31[22m[39m
    [90m 99| [39m        [33m.[39m[34msend[39m({ email[33m:[39m validEmail })[33m;[39m
    [90m100| [39m
    [90m101| [39m      [34mexpect[39m(response[33m.[39mstatus)[33m.[39m[34mtoBe[39m([34m200[39m)[33m;[39m
    [90m   | [39m                              [31m^[39m
    [90m102| [39m      [34mexpect[39m(response[33m.[39mbody[33m.[39mmessage)[33m.[39m[34mtoBe[39m(
    [90m103| [39m        [32m"Email for reset password sent successfully"[39m[33m,[39m

[31m[2m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[4/4]‚éØ[22m[39m

[31m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[1m[7m Unhandled Errors [27m[22m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[39m
[31m[1m
Vitest caught 3 unhandled errors during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.[22m[39m

[31m‚éØ‚éØ‚éØ‚éØ‚éØ[1m[7m Uncaught Exception [27m[22m‚éØ‚éØ‚éØ‚éØ‚éØ[39m
[31m[1mError[22m: listen EADDRINUSE: address already in use :::8080[39m
[90m [2m‚ùØ[22m Server.setupListenHandle [as _listen2] node:net:[2m1898:16[22m[39m
[90m [2m‚ùØ[22m listenInCluster node:net:[2m1946:12[22m[39m
[90m [2m‚ùØ[22m Server.listen node:net:[2m2044:7[22m[39m
[90m [2m‚ùØ[22m Function.listen node_modules/express/lib/application.js:[2m635:24[22m[39m
[36m [2m‚ùØ[22m src/app.ts:[2m94:20[22m[39m
    [90m 92| [39m  })[33m;[39m
    [90m 93| [39m
    [90m 94| [39m[35mconst[39m server [33m=[39m app[33m.[39m[34mlisten[39m([33mPORT[39m[33m,[39m () [33m=>[39m {
    [90m   | [39m                   [31m^[39m
    [90m 95| [39m  console[33m.[39m[34mlog[39m([32m`Server running on port [39m[36m${[39m[33mPORT[39m[36m}[39m[32m`[39m)[33m;[39m
    [90m 96| [39m  console[33m.[39m[34mlog[39m([32m`Swagger docs: http://localhost:[39m[36m${[39m[33mPORT[39m[36m}[39m[32m/api-docs`[39m)[33m;[39m
[90m [2m‚ùØ[22m processTicksAndRejections node:internal/process/task_queues:[2m95:5[22m[39m
[90m [2m‚ùØ[22m VitestExecutor.runModule node_modules/vite-node/dist/client.mjs:[2m399:5[22m[39m
[90m [2m‚ùØ[22m VitestExecutor.directRequest node_modules/vite-node/dist/client.mjs:[2m381:5[22m[39m
[90m [2m‚ùØ[22m VitestExecutor.cachedRequest node_modules/vite-node/dist/client.mjs:[2m206:14[22m[39m
[90m [2m‚ùØ[22m VitestExecutor.dependencyRequest node_modules/vite-node/dist/client.mjs:[2m259:12[22m[39m

[31m[2m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[22m[39m
[31m[1mSerialized Error:[22m[39m [90m{ code: 'EADDRINUSE', errno: -4091, syscall: 'listen', address: '::', port: 8080 }[39m
[31mThis error originated in "[1mtests/app.test.ts[22m" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.[39m
[31mThe latest test that might've caused the error is "[1mtests/app.test.ts[22m". It might mean one of the following:
- The error was thrown, while Vitest was running this test.
- If the error occurred after the test had been completed, this was the last documented test before it was thrown.[39m

[31m‚éØ‚éØ‚éØ‚éØ‚éØ[1m[7m Uncaught Exception [27m[22m‚éØ‚éØ‚éØ‚éØ‚éØ[39m
[31m[1mError[22m: listen EADDRINUSE: address already in use :::8080[39m
[90m [2m‚ùØ[22m Server.setupListenHandle [as _listen2] node:net:[2m1898:16[22m[39m
[90m [2m‚ùØ[22m listenInCluster node:net:[2m1946:12[22m[39m
[90m [2m‚ùØ[22m Server.listen node:net:[2m2044:7[22m[39m
[90m [2m‚ùØ[22m Function.listen node_modules/express/lib/application.js:[2m635:24[22m[39m
[36m [2m‚ùØ[22m src/app.ts:[2m94:20[22m[39m
    [90m 92| [39m  })[33m;[39m
    [90m 93| [39m
    [90m 94| [39m[35mconst[39m server [33m=[39m app[33m.[39m[34mlisten[39m([33mPORT[39m[33m,[39m () [33m=>[39m {
    [90m   | [39m                   [31m^[39m
    [90m 95| [39m  console[33m.[39m[34mlog[39m([32m`Server running on port [39m[36m${[39m[33mPORT[39m[36m}[39m[32m`[39m)[33m;[39m
    [90m 96| [39m  console[33m.[39m[34mlog[39m([32m`Swagger docs: http://localhost:[39m[36m${[39m[33mPORT[39m[36m}[39m[32m/api-docs`[39m)[33m;[39m
[90m [2m‚ùØ[22m processTicksAndRejections node:internal/process/task_queues:[2m95:5[22m[39m
[90m [2m‚ùØ[22m VitestExecutor.runModule node_modules/vite-node/dist/client.mjs:[2m399:5[22m[39m
[90m [2m‚ùØ[22m VitestExecutor.directRequest node_modules/vite-node/dist/client.mjs:[2m381:5[22m[39m
[90m [2m‚ùØ[22m VitestExecutor.cachedRequest node_modules/vite-node/dist/client.mjs:[2m206:14[22m[39m
[90m [2m‚ùØ[22m VitestExecutor.dependencyRequest node_modules/vite-node/dist/client.mjs:[2m259:12[22m[39m

[31m[2m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[22m[39m
[31m[1mSerialized Error:[22m[39m [90m{ code: 'EADDRINUSE', errno: -4091, syscall: 'listen', address: '::', port: 8080 }[39m
[31mThis error originated in "[1mtests/book/book.test.ts[22m" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.[39m
[31mThe latest test that might've caused the error is "[1mtests/book/book.test.ts[22m". It might mean one of the following:
- The error was thrown, while Vitest was running this test.
- If the error occurred after the test had been completed, this was the last documented test before it was thrown.[39m

[31m‚éØ‚éØ‚éØ‚éØ‚éØ[1m[7m Uncaught Exception [27m[22m‚éØ‚éØ‚éØ‚éØ‚éØ[39m
[31m[1mError[22m: listen EADDRINUSE: address already in use :::8080[39m
[90m [2m‚ùØ[22m Server.setupListenHandle [as _listen2] node:net:[2m1898:16[22m[39m
[90m [2m‚ùØ[22m listenInCluster node:net:[2m1946:12[22m[39m
[90m [2m‚ùØ[22m Server.listen node:net:[2m2044:7[22m[39m
[90m [2m‚ùØ[22m Function.listen node_modules/express/lib/application.js:[2m635:24[22m[39m
[36m [2m‚ùØ[22m src/app.ts:[2m94:20[22m[39m
    [90m 92| [39m  })[33m;[39m
    [90m 93| [39m
    [90m 94| [39m[35mconst[39m server [33m=[39m app[33m.[39m[34mlisten[39m([33mPORT[39m[33m,[39m () [33m=>[39m {
    [90m   | [39m                   [31m^[39m
    [90m 95| [39m  console[33m.[39m[34mlog[39m([32m`Server running on port [39m[36m${[39m[33mPORT[39m[36m}[39m[32m`[39m)[33m;[39m
    [90m 96| [39m  console[33m.[39m[34mlog[39m([32m`Swagger docs: http://localhost:[39m[36m${[39m[33mPORT[39m[36m}[39m[32m/api-docs`[39m)[33m;[39m
[90m [2m‚ùØ[22m processTicksAndRejections node:internal/process/task_queues:[2m95:5[22m[39m
[90m [2m‚ùØ[22m VitestExecutor.runModule node_modules/vite-node/dist/client.mjs:[2m399:5[22m[39m
[90m [2m‚ùØ[22m VitestExecutor.directRequest node_modules/vite-node/dist/client.mjs:[2m381:5[22m[39m
[90m [2m‚ùØ[22m VitestExecutor.cachedRequest node_modules/vite-node/dist/client.mjs:[2m206:14[22m[39m
[90m [2m‚ùØ[22m VitestExecutor.dependencyRequest node_modules/vite-node/dist/client.mjs:[2m259:12[22m[39m

[31m[2m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[22m[39m
[31m[1mSerialized Error:[22m[39m [90m{ code: 'EADDRINUSE', errno: -4091, syscall: 'listen', address: '::', port: 8080 }[39m
[31mThis error originated in "[1mtests/auth/auth.test.ts[22m" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.[39m
[31mThe latest test that might've caused the error is "[1mtests/auth/auth.test.ts[22m". It might mean one of the following:
- The error was thrown, while Vitest was running this test.
- If the error occurred after the test had been completed, this was the last documented test before it was thrown.[39m
[31m‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ‚éØ[39m

[2m Test Files [22m [1m[31m2 failed[39m[22m[2m | [22m[1m[32m2 passed[39m[22m[90m (4)[39m
[2m      Tests [22m [1m[31m4 failed[39m[22m[2m | [22m[1m[32m43 passed[39m[22m[90m (47)[39m
[2m     Errors [22m [1m[31m3 errors[39m[22m
[2m   Start at [22m 20:28:49
[2m   Duration [22m 59.52s


[1m[7m[31m FAIL [39m[27m[22m[31m Tests failed. Watching for file changes...[39m
       [2mpress [22m[1mh[22m[2m to show help[22m[2m, [22m[2mpress [22m[1mq[22m[2m to quit[22m
[31mCancelling test run. Press CTRL+c again to exit forcefully.
[39m
